[profile.release]
panic = "unwind"

[workspace]
members = [
    "node",
    "node/cli",
    "node/service",
    "rpc",
    "runtime/solo",
    "runtime/bajun",
    "runtime/ajuna",
    "pallets/ajuna-awesome-avatars",
    "pallets/battle-mogs",
    "primitives",
    "ajuna-common",
    "ajuna-test",
]
