version: "3.7"

services:
  ajuna-solo:
    image: backend-devel.azurecr.io/node
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - features=solo
        - bin=ajuna-solo
    command: --dev --tmp --unsafe-ws-external --unsafe-rpc-external
    ports:
      - 9944:9944
      - 9933:9933